chore: workflows

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,10 +1,10 @@
 name: Deploy
 
 on:
-  push:
-    tags:
-      - 'v*-dev'
-      - 'v*-main'
+  workflow_run:
+    workflows: ['Tagging']
+    types:
+      - completed
 
 jobs:
   build:
@@ -19,52 +19,59 @@ jobs:
       contents: read
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Set Node.js version
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node }}
+      - name: Get tag from previous workflow
+        id: get-tag
+        run: |
+          git fetch --tags
+          TAG=$(git describe --tags --abbrev=0)
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
 
-    - name: Set Environment Variables
-      id: set-env
-      run: |
-        if [[ ${{ github.ref_name }} == *"-dev" ]]; then
-          echo "${{ secrets.ENV_DEV }}" > .env
-          echo "AWS_ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_PREFIX }}-dev" >> $GITHUB_ENV
-        elif [[ ${{ github.ref_name }} == *"-main" ]]; then
-          echo "${{ secrets.ENV_PROD }}" > .env
-          echo "AWS_ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_PREFIX }}-prod" >> $GITHUB_ENV
-        else
-          echo "Invalid tag format. Tag must end with -dev or -main"
-          exit 1
-        fi
+      - name: Set Node.js version
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node }}
 
-    - name: Build Application
-      run: |
-        npm ci
-        npm run build
+      - name: Set Environment Variables
+        id: set-env
+        run: |
+          if [[ ${{ steps.get-tag.outputs.tag }} == *"-dev" ]]; then
+            echo "${{ secrets.ENV_DEV }}" > .env
+            echo "AWS_ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_PREFIX }}-dev" >> $GITHUB_ENV
+          elif [[ ${{ steps.get-tag.outputs.tag }} == *"-main" ]]; then
+            echo "${{ secrets.ENV_PROD }}" > .env
+            echo "AWS_ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_PREFIX }}-prod" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format. Tag must end with -dev or -main"
+            exit 1
+          fi
 
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-region: ${{ secrets.AWS_REGION }}
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: Build Application
+        run: |
+          npm ci
+          npm run build
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v2
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ secrets.AWS_REGION }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-    - name: Build, tag, and push image to Amazon ECR
-      id: build-image
-      env:
-        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
-      run: |
-        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }} .
-        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }}
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-tag.outputs.tag }} .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-tag.outputs.tag }}
 
   deploy:
     needs: build
@@ -74,25 +81,25 @@ jobs:
       contents: read
 
     steps:
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-region: ${{ secrets.AWS_REGION }}
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ secrets.AWS_REGION }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-    - name: Fill in the new image ID in the Amazon ECS task definition
-      id: task-definition
-      uses: aws-actions/amazon-ecs-render-task-definition@v4
-      with:
-        task-definition: ${{ secrets.AWS_ECS_TASK_DEFINITION }}
-        container-name: ${{ secrets.AWS_ECS_CONTAINER_NAME }}
-        image: ${{ needs.build.outputs.image }}
+      - name: Fill in the new image ID in the Amazon ECS task definition
+        id: task-definition
+        uses: aws-actions/amazon-ecs-render-task-definition@v4
+        with:
+          task-definition: ${{ secrets.AWS_ECS_TASK_DEFINITION }}
+          container-name: ${{ secrets.AWS_ECS_CONTAINER_NAME }}
+          image: ${{ needs.build.outputs.image }}
 
-    - name: Deploy Amazon ECS task definition
-      uses: aws-actions/amazon-ecs-deploy-task-definition@v4
-      with:
-        task-definition: ${{ steps.task-definition.outputs.task-definition }}
-        service: ${{ secrets.AWS_ECS_SERVICE }}
-        cluster: ${{ secrets.AWS_ECS_CLUSTER }}
-        wait-for-service-stability: true 
+      - name: Deploy Amazon ECS task definition
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v4
+        with:
+          task-definition: ${{ steps.task-definition.outputs.task-definition }}
+          service: ${{ secrets.AWS_ECS_SERVICE }}
+          cluster: ${{ secrets.AWS_ECS_CLUSTER }}
+          wait-for-service-stability: true
