chore: tagging.yaml

diff --git a/.github/workflows/tagging.yaml b/.github/workflows/tagging.yaml
--- a/.github/workflows/tagging.yaml
+++ b/.github/workflows/tagging.yaml
@@ -1,10 +1,14 @@
 name: Tagging
 
 on:
-  workflow_run:
-    workflows: ['Version']
-    types:
-      - completed
+  push:
+    branches: ['main', 'dev']
+    paths:
+      - 'src/**'
+      - 'package*.json'
+      - 'tsconfig*.json'
+      - 'nset-cli.json'
+      - 'Dockerfile'
 
 jobs:
   version:
@@ -13,18 +17,45 @@ jobs:
     strategy:
       matrix:
         node: [20]
-        branch: [dev, main]
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          ref: ${{ matrix.branch }}
 
-      - name: Tagging
+      - name: Initialize
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node }}
+
+      - name: Set Environment Variables
         run: |
+          if [ "${{ github.ref_name }}" == "dev" ]; then
+            echo "TAG_SUFFIX=dev" >> $GITHUB_ENV
+          elif [ "${{ github.ref_name }}" == "main" ]; then
+            echo "TAG_SUFFIX=prod" >> $GITHUB_ENV
+          else
+            echo "Invalid ref name. Branch name must be dev or main"
+            exit 1
+          fi
+
           version=$(cat package.json | grep '"version"' | awk -F '"' '{print $4}')
-          tag=${version}-${matrix.branch}
-          git tag $tag
-          git push origin $tag
+          commit_hash=$(git rev-parse --short HEAD)
+          tag=${version}-${commit_hash}-${{ env.TAG_SUFFIX }}
+
+          echo "tag=$tag" >> $GITHUB_OUTPUT
+
+      - name: Set Version
+        run: |
+          if [ "${{ env.TAG_SUFFIX }}" == "prod" ]; then
+            git config --global user.name "actions"
+            git config --global user.email "actions@github.com"
+            npm version patch
+            git push origin ${{ github.ref_name }}
+          fi
+
+      - name: Push Tag
+        run: |
+          git tag -a ${{ env.TAG_NAME }} -m "Tagging ${{ env.TAG_NAME }}"
+          git push origin ${{ env.TAG_NAME }}
